default: &default
  adapter: postgresql
  host: postgres
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  url: <%= ENV["DATABASE_URL"] %>
  username: postgres
  password: postgres

development:
  database: account_development
  <<: *default

test:
  <<: *default
  database: <%= ENV["DATABASE_URL"] %>_test

production:
  <<: *default